# This is a basic workflow to help you get started with Actions

name: Portfolio Deployment Workflow - Develop Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # name of the deployment
    name: Portfolio Deployment Workflow - Develop Environment
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@master
      - run: npm install
      - run: git config user.name "Ravi Jayaraman" && git config user.email "ravijayaraman13894@gmail.com"
      - run: npm run lint
      - run: npm run build
